const arquivo = [
  {
    id: 1,
    nome: "Dra. Ana Silva",
    role: "Adm",
    clinica: "Nutrição Saudável",
    especialidadesNutricao: ["Nutrição Clínica", "Nutrição Esportiva"],
    cidade: "São Paulo",
    uf: "SP",
    localizacao: "Rua São João, 123",
    imagemPerfil: "/Assets/medico.png",
  },
  {
    id: 2,
    nome: "Marcos Souza",
    clinica: "Nutrição Total",
    role: "Adm",
    especialidadesNutricao: ["Nutrição Infantil", "Nutrição Funcional"],
    cidade: "Rio de Janeiro",
    uf: "RJ",
    localizacao: "Avenida Exemplo, 456",
    imagemPerfil: "../../Assets/avatar_1.png",
  },
  {
    id: 3,
    nome: "Carla Santos",
    role: "Nutricionista",
    clinica: "Nutrição Equilíbrio",
    especialidadesNutricao: ["Nutrição Geriátrica", "Nutrição Escolar"],
    cidade: "Belo Horizonte",
    uf: "MG",
    localizacao: "Travessa da Alimentação, 789",
    imagemPerfil: "../../Assets/medico.png",
  },
  {
    id: 4,
    nome: "Dr. Felipe Pereira",
    role: "Nutricionista",
    clinica: "Nutrição Vital",
    especialidadesNutricao: ["Nutrição Esportiva", "Nutrição Funcional"],
    cidade: "Porto Alegre",
    uf: "RS",
    localizacao: "Praça da Saúde, 101",
    imagemPerfil: "../../Assets/avatar_1.png",
  },
  {
    id: 5,
    nome: "Dra. Patricia Almeida",
    clinica: "Nutrição Balanceada",
    role: "Nutricionista",
    especialidadesNutricao: ["Nutrição Clínica", "Nutrição Comportamental"],
    cidade: "Brasília",
    uf: "DF",
    localizacao: "Avenida da Nutrição, 789",
    imagemPerfil: "../../Assets/medico.png",
  },
  {
    id: 6,
    nome: "Dr. Ricardo Mendes",
    clinica: "Nutrição e Saúde",
    especialidadesNutricao: ["Nutrição Esportiva", "Nutrição Infantil"],
    role: "Nutricionista",
    cidade: "Salvador",
    uf: "BA",
    localizacao: "Rua da Saúde, 567",
    imagemPerfil: "../../Assets/avatar_1.png",
  },
  {
    id: 7,
    nome: "Dra. Juliana Ferreira",
    clinica: "Nutrição Ativa",
    role: "Nutricionista",
    especialidadesNutricao: ["Nutrição Funcional", "Nutrição Vegetariana"],
    cidade: "Salvador",
    uf: "BA",
    localizacao: "Praça da Nutrição, 234",
    imagemPerfil: "../../Assets/medico.png",
  },
];

export default arquivo;
